/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f103c6.h"
#include "stm32f103c6_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void)
{
	GPIOC_CLOCK_EN();
	GPIO_PinConfig_t PINC0;
	PINC0.GPIO_PinNumber=GPIO_PIN_13;
	PINC0.GPIO_Mode=GPIO_MODE_OUTPUT_PP;
	PINC0.GPIO_Speed=GPIO_SPEED_10M;

	MCAL_GPIO_Init(GPIOC,&PINC0);



    /* Loop forever */
	while(1)
	{
		MCAL_GPIO_Write_Pin(GPIOC, GPIO_PIN_13, GPIO_PIN_VALUE_HIGH);
		for(volatile int i=0;i<100000;i++);
		MCAL_GPIO_Write_Pin(GPIOC, GPIO_PIN_13, GPIO_PIN_VALUE_LOW);
		for(volatile int i=0;i<100000;i++);
	};
}
